version: '3'

services:
  frontend:
    build: ./frontend/iot
    ports:
      - "3000:3000"
    depends_on:
      - mqtt-transmit

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - mosquitto
    network_mode: "host"

  mysql:
    container_name: mysql
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: bs
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    restart: always
    network_mode: "host"

  mosquitto:
    image: eclipse-mosquitto:2.0.14
    ports:
      - "1883:1883"
    network_mode: "host"
      
  mqtt-transmit:
    build: ./mqtt
    depends_on:
      - backend
    network_mode: "host"